In [1]:
import pandas as pd
import re

In [2]:
with open('Chat de WhatsApp con Ciencia de datos Acatlán.txt') as f:
    lines = f.readlines()

In [3]:
df=pd.DataFrame(lines)
df

                                                      0
0     09/08/21 2:15 p. m. - Los mensajes y las llama...
1     09/08/21 2:14 p. m. - ‎Gabo CD creó el grupo "...
2     09/08/21 2:15 p. m. - Te uniste mediante el en...
3     09/08/21 2:15 p. m. - ‎Gustavo Alvarez se unió...
4     09/08/21 2:25 p. m. - ‎Francisco CD se unió us...
...                                                 ...
8052  04/11/22 7:59 p. m. - Mi RucA: <Multimedia omi...
8053  05/11/22 6:49 a. m. - Francisco CD: Buenos día...
8054  05/11/22 6:50 a. m. - Mi RucA: Quién sabe, por...
8055  05/11/22 6:51 a. m. - Francisco CD: Vaaa le pr...
8056  05/11/22 6:51 a. m. - Francisco CD: Gracias Ab...

[8057 rows x 1 columns]

In [4]:
df=df[0].str.replace('^[\s\S]+:','',regex=True)

In [5]:
df.to_csv('platica.csv',index=False)

In [6]:
df=pd.read_csv('platica.csv')

In [7]:
df.head()

                                                   0
0  15 p. m. - Los mensajes y las llamadas están c...
1  14 p. m. - ‎Gabo CD creó el grupo "Ciencia de ...
2  15 p. m. - Te uniste mediante el enlace de inv...
3  15 p. m. - ‎Gustavo Alvarez se unió usando el ...
4  25 p. m. - ‎Francisco CD se unió usando el enl...

In [8]:
inicio=616+556+304+81+217+318+82

In [9]:
lista=[]
for indice,fila in df.iloc[inicio:].iterrows():
    print(fila[0])
    sentimiento=int(input())
    lista.append(sentimiento)

 <Multimedia omitido>

-2
 De ver la película

0
 Y también bebí en la película

0
 Jajaja

1
 Pedí mi tradicional coquita

1
 Y le eche ron

1
 Jajaaha

1
 <Multimedia omitido>

-2
 <Multimedia omitido>

-2
 Que solo con 50 registros

0
 Por locación

0
 Gracias🫶

1
 Aún así es un verg

-1
 Si encuentran como tomar en menos tiempo

0
 Avisan

0
 Va

1
 <Multimedia omitido>

-2
 Porque son 3.33 horas

0
 <Multimedia omitido>

-2
 pero son 20 en total

0
 o sea mucho menos

0
 Nop

0
 Porque ve

0
 Son 20 locaciones

0
 si el dijo jajaja le pregunte

0
 50 registros

0
 Cada registro se tarda 4s

0
 Por los 3 diferentes horarios

0
 <Multimedia omitido>

-2
 Entre 60 da 200 minutos

0
 <Multimedia omitido>

-2
 donde esta su cubiculo? jajaj

0
 No se

0
 Por?

0
 <Multimedia omitido>

-2
 Dile que le baje a las locaciones

0
 Que con 5 o 10

0
 Que no mame xd

-1
 es que si es una cerdada 3 horas

-1
 si la clase dura 2 horas

0
 Yo ya lo hice bajarle 50 registros

0
 Ya tu bájale las locaciones

0
 <Multimedia omitido>

-2
 O que nos dé sensores chidos

0
 Lo que quiera

0
 <Multimedia omitido>

-2
 Van a ir hoy?

0
 <Multimedia omitido>

-2
 No wee

0
 Jeje

1
 Yo no

0
 Fuck

-1
 Eliminaste este mensaje.

-2
 Es que ya le pedimos que no diera una clase

0
 No quiero decirle de nuevo

-1
 <Multimedia omitido>

0
 Pero

0
 Alguien si tenia pensando ir?

0
 Nosotros pero porque ya estamos en la escuela jaja pero igual no creo que hagamos algo importante

0
 Va

1
 Entonces solo van a ir tu y abi?

0
 <Multimedia omitido>

-2
 🤣

1
 No sé, supongo

0
 Así les tocó una vez a gabo y a ti no?

0
 @5215543376293 tú no vienes?

0
 Ei

0
 <Multimedia omitido>

-2
 no perdon jeje

0
 Va a explicarnos del proyecto final

0
 Martes 24 lo tenemos que presentar

0
 Chale

-1
 <Multimedia omitido>

-2
 Nos va a dar la próxima semana para trabajar en el, no hay clases de viz la próxima semana

0
 Va

0
 Gracias

1
 @5215538430946

-2
 Avisan que graficas harán ustedes

0
 Para ponernos de acuerdo nosotros

0
 <Multimedia omitido>

-2
 Va

1
 <Multimedia omitido>

-2
 Nosotros haremos esos

k

ValueError: invalid literal for int() with base 10: 'k'

In [10]:
#616
final=len(lista)
final

82

In [11]:
df2=df.iloc[inicio:inicio+final].copy()

In [12]:
df2=df2.reset_index()

In [13]:
df2['sentimiento']=pd.Series(lista)

In [14]:
df2=df2.drop('index',axis=1)
df2

                                       0  sentimiento
0                 <Multimedia omitido>\n           -2
1                   De ver la película\n            0
2        Y también bebí en la película\n            0
3                               Jajaja\n            1
4          Pedí mi tradicional coquita\n            1
..                                   ...          ...
77   Avisan que graficas harán ustedes\n            0
78   Para ponernos de acuerdo nosotros\n            0
79                <Multimedia omitido>\n           -2
80                                  Va\n            1
81                <Multimedia omitido>\n           -2

[82 rows x 2 columns]

In [15]:
df2.to_csv('final.csv',index=False,mode='a',index_label=False)